In [1]:
import numpy as np
import pandas as pd
import statistics as st

In [3]:
df = pd.read_csv("Iris (1).csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
summary = df.groupby('Species')['SepalLengthCm'].describe()

In [6]:
summary

                 count   mean       std  min    25%  50%  75%  max
Species
Iris-setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [10]:
summary_stats = df.groupby('Species').agg(['mean', 'median', 'min', 'max', 'std'])

In [11]:
summary_stats

                    Id                            SepalLengthCm              \
                  mean median  min  max       std          mean median  min
Species
Iris-setosa       25.5   25.5    1   50  14.57738         5.006    5.0  4.3
Iris-versicolor   75.5   75.5   51  100  14.57738         5.936    5.9  4.9
Iris-virginica   125.5  125.5  101  150  14.57738         6.588    6.5  4.9

                                ... PetalLengthCm                             \
                 max       std  ...          mean median  min  max       std
Species                         ...
Iris-setosa      5.8  0.352490  ...         1.464   1.50  1.0  1.9  0.173511
Iris-versicolor  7.0  0.516171  ...         4.260   4.35  3.0  5.1  0.469911
Iris-virginica   7.9  0.635880  ...         5.552   5.55  4.5  6.9  0.551895

                PetalWidthCm
                        mean median  min  max       std
Species
Iris-setosa            0.244    0.2  0.1  0.6  0.107210
Iris-versicolor        1.326    1.3  1.0  1.8  0.197753
Iris-virginica         2.026    2.0  1.4  2.5  0.274650

[3 rows x 25 columns]

In [12]:
summary_stats.columns = ['_'.join(col).strip() for col in summary_stats.columns.values]

In [14]:
summary_stats.columns

Index(['Id_mean', 'Id_median', 'Id_min', 'Id_max', 'Id_std',
       'SepalLengthCm_mean', 'SepalLengthCm_median', 'SepalLengthCm_min',
       'SepalLengthCm_max', 'SepalLengthCm_std', 'SepalWidthCm_mean',
       'SepalWidthCm_median', 'SepalWidthCm_min', 'SepalWidthCm_max',
       'SepalWidthCm_std', 'PetalLengthCm_mean', 'PetalLengthCm_median',
       'PetalLengthCm_min', 'PetalLengthCm_max', 'PetalLengthCm_std',
       'PetalWidthCm_mean', 'PetalWidthCm_median', 'PetalWidthCm_min',
       'PetalWidthCm_max', 'PetalWidthCm_std'],
      dtype='object')

In [18]:
setosa_stats = df[df['Species'] =='Iris-setosa'].describe()
versicolor_stats = df[df['Species'] == 'Iris-versicolor'].describe()
virginica_stats = df[df['Species'] == 'Iris-virginica'].describe()

In [19]:
# Display the statistical details for each species
print("Statistical details for Iris-setosa:")
print(setosa_stats)
print("\nStatistical details for Iris-versicolor:")
print(versicolor_stats)
print("\nStatistical details for Iris-virginica:")
print(virginica_stats)

Statistical details for Iris-setosa:
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

Statistical details for Iris-versicolor:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

Statistical details for Iris-virginica:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000